sonar.projectKey=atablebzh-ship-it_prix-du-jour-app
sonar.organization=atablebzh-ship-it

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.sources=api,lib
sonar.exclusions=**/node_modules/**,**/*.test.js,**/coverage/**
sonar.tests=test
